var colors = ["#fc755d","#d1fedd","#4dffb8", "#e3ff57", "#8d21ff", "#ffe55c", "#ff339d", "#73e3ff", "#ff6f3f", "#ee3fff", "#513fff", "#56ff5f"];

var colorsDark = ["#68aa14", "#876027", "#016d57", "#2f1d3e", "#4d0840", "#421d1a", "#ff0000", "#214365", "#909000", "#03c", "#2d5"];

var texts = ["wolf", "forest", "boar", "horse", "sheep", "potion", "app", "game", "website", "quarry", "stone", "copper", "uranium", "radiation", "pie", "cat", "car", "box", "dog", "hat", "carrot", "apple", "banana", "orange", "pear", "grape", "watermelon", "winter", "summer", "tree", "pine", "birch", "flower", "tower", "building", "bus", "train", "wheel", "oil", "night", "day", "sun", "moon", "star", "cloud", "rain", "snow", "wind", "hammer", "nail", "wish", "death", "time", "year", "beaker", "bracket", "square", "question", "answer", "pencil", "pen", "paper", "book", "bookshelf", "poison", "lava", "This is a really long text which I just wanted you to be able to see and is very different from the other possible texts generated by this which are single nouns."];

var nameBitsAdjAdj = ["Very", "Highly", "Slightly", "Mildly" ,"Sort of", "Vaguely", "Quite", "Possibly", "Decisively", "Considerably", "Absolutely", "Not at all", "Extremely"];
var nameBitsAdj = ["Irregular", "Fancy", "Great", "Grand", "Happy", "Lucky", "Magnificent", "Nice", "Noble", "Perfect", "Pretty", "Quiet", "Rare", "Unfortunate", "Despicable", "Dangerous", "Dull", "Hated", "Honorable", "Mysterious", "Mystical", "Ridiculous", "Bottomless"];
var nameBitsContainer = ["Dump", "Box", "Chest", "Crate", "Cupboard", "Drawer", "Garbage Pile", "Pool", "Sack", "Stock", "Cave Full", "Pit"];
var nameBitsPluralNoun = ["Birds", "Cats", "Dogs", "Horses", "Pigs", "Sheep", "Winds", "Knives", "Gems", "Coins", "Wands", "Queens", "Forts", "Moons", "Apples", "Clouds", "Time Crystals", "Bears", "Answers", "Bananas", "Knights", "Cattle", "Wheels", "Papers", "Books", "Snows", "Rains", "Oils", "Carrots", "Clubs", "Shovels", "Treasures", "Stones", "Nights", "Years", "Trains", "Nobles", "Oils", "Hammers", "Nails", "Repairs", "Tools", "Maps", "Naps", "Wishes", "Winters", "Times", "Pears", "Pines", "Brackets", "Stencils", "Roots", "Forests", "Towers", "Mushrooms", "Peppers", "Orbs", "Spells", "Wands", "Castles"];

var rps = ["rock", "paper", "scissors"];

var randomButtons = [
  ["Change background color", function() {changeBackgroundColor()}],
  ["Change text color", function() {changeTextColor()}],
  ["Give me a word", function() {makeText()}],
  ["Make me a name", function() {makeName()}],
  ["RPS", function() {makeRps()}],
  ["Does nothing", function() {}],
  ["Make me an egg", function() {makeEgg()}],
  ["Make seven buttons", function() {for(i=0; i<7; i++){makeButton()}}],
  ["Make me a square", function() {makeSquare()}]
];

var commonEggs = ["crow egg", "chicken egg", "robin egg", "cracked egg", "Easter egg", "snake egg"];

var uncommonEggs = ["big egg", "small egg", "parrot egg" ,"bouncy egg", "platypus egg"];

var rareEggs = ["dodo egg", "radioactive egg", "double yolk egg","shark egg","dinosaur egg"];

var mythicEggs = [["f","r","a","c","t","a","l"," e","g","g"],["c","u","b","e"," ","e","g","g"], ["tr","ia","n","g","ul","a","r"," e","g","g"], ["he","x","a","g","o","n","al"," e","g","g"], ["d","r","a","g","o","n"," ","e","g","g"]];

//10 colors
var mythicEggColors = ["#ff0000", "#ff8800", "#ffff00", "#00ff00", "#00ff88", "#00ffff", "#0088ff", "#0000ff", "#8800ff", "#ff00ff"];

var root = document.querySelector(':root');

var buttonArea = document.getElementById("button-area");

var randomArea = document.getElementById("randomness-area");

function changeBackgroundColor()
{
  root.style.setProperty('--background-color', colors[Math.floor(Math.random() * colors.length)]);
}

function changeTextColor()
{
  root.style.setProperty('--text-color', colorsDark[Math.floor(Math.random() * colorsDark.length)]);
}

function makeText()
{
  var p = document.createElement("p");
  p.innerHTML = texts[Math.floor(Math.random() * texts.length)];
  randomArea.appendChild(p);
}

function makeName()
{
  var p = document.createElement("p");
  var name = "";
  
  if(Math.random() < 0.3)
  {
    name+= nameBitsAdjAdj[Math.floor(Math.random() * nameBitsAdjAdj.length)] + " ";
  }
  
  name+= nameBitsAdj[Math.floor(Math.random() * nameBitsAdj.length)] + " ";
  
  if(Math.random() < 0.3)
  {
    name+= nameBitsContainer[Math.floor(Math.random() * nameBitsContainer.length)] + " of ";
  }
  
  name+= nameBitsPluralNoun[Math.floor(Math.random() * nameBitsPluralNoun.length)];
  
  p.innerHTML = name;
  randomArea.appendChild(p);
}

function makeRps()
{
  var p = document.createElement("p");
  p.innerHTML = "I choose " + rps[Math.floor(Math.random() * rps.length)];
  randomArea.appendChild(p);
}

function makeButton()
{
  var buttonContainer = document.createElement("div");
  var button = document.createElement("button");
  var buttonToMake = randomButtons[Math.floor(Math.random() * randomButtons.length)];
  
  buttonContainer.className = "button-container";
  button.type = "button";
  button.innerHTML = buttonToMake[0];
  button.onclick = buttonToMake[1];
  
  buttonArea.appendChild(buttonContainer);
  buttonContainer.appendChild(button);
}

function makeEgg()
{
  var p = document.createElement("p");
  randomArea.appendChild(p);
  var rarity_random_value = Math.random();
  if(rarity_random_value < 0.65)
  {
    var span = document.createElement("span");
    var egg = commonEggs[Math.floor(Math.random() * commonEggs.length)];
    span.style.color = "#8f350c";
    span.innerHTML = egg;
    p.appendChild(span);
  }
  else if((rarity_random_value-0.65) < 0.25)
  {
    var span = document.createElement("span");
    var egg = uncommonEggs[Math.floor(Math.random() * uncommonEggs.length)];
    span.style.color = "#a9cbd0";
    span.innerHTML = egg;
    p.appendChild(span);
  }
  else if((rarity_random_value-(0.65+0.25)) < 0.09)
  {
    var span = document.createElement("span");
    var egg = rareEggs[Math.floor(Math.random() * rareEggs.length)];
    span.style.color = "#f2bd36";
    span.innerHTML = egg;
    p.appendChild(span);
  }
  else
  {
    var egg = mythicEggs[Math.floor(Math.random() * mythicEggs.length)];
    for(segmentNumber in egg)
    {
      var span = document.createElement("span");
      span.style.color = mythicEggColors[segmentNumber];
      span.innerHTML = egg[segmentNumber];
      p.appendChild(span);
    }
  }
}

function makeSquare()
{
  var p = document.createElement("p");
  p.innerHTML = Math.floor(Math.random() * 150) ** 2;
  randomArea.appendChild(p);
}